services:
  app:
    container_name: bee_mely
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - '8080:8080'
    command: npm start
